# generates TypeScript declarations (.d.ts files)
# output service definitions as both .js and .d.ts files in the structure required by grpc-web
# output service definitions as both .js and .d.ts files in the structure required by grpc-node
# .//build.sh

PROJECT_BIN="./node_modules/.bin"
# protoc路径
PROTOC="C:\\Proto\\protoc-3.5.0-win32\\bin\\protoc.exe"
# *.proto文件的存放路径
PROTO_DIR="proto"
# Directory to write generated code to (.js and .d.ts files)
GRPC_OUT=".\\src\\grpc"

# Generating TypeScript Definitions for CommonJS modules generated by protoc
# Path to ts-protoc-gen
PROTOC_GEN_TS=".\\node_modules\\.bin\\protoc-gen-ts.cmd"


# Generating gRPC Service Stubs for use with grpc-node
$PROTOC \
    --plugin="protoc-gen-ts=${PROTOC_GEN_TS}" \
    --js_out="import_style=commonjs,binary:${GRPC_OUT}" \
    --ts_out="service=grpc-node,mode=grpc-js:${GRPC_OUT}" \
    -I=$PROTO_DIR users.proto